apiVersion: batch/v1
kind: Job
metadata:
  name: tilelang-gemm-job
spec:
  template:
    spec:
      containers:
      - name: tilelang-container
        image: thefrenchstuff/tilelang-gemm:latest
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"  # Allocate enough memory for TileLang installation
          requests:
            memory: "4Gi"
        # You can add environment variables if needed
        env:
        - name: TILELANG_CUDA_ARCH
          value: "sm_90"  # For H100 GPUs
      restartPolicy: Never
