apiVersion: v1
kind: Pod
metadata:
  name: tilelang-gemm
spec:
  containers:
  - name: tilelang-container
    image: nvidia/cuda:11.8.0-devel-ubuntu22.04  # You might need a different image with PyTorch and TileLang
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1  # Request 1 GPU
